version: "3.9"

services:
  wiremock:
    image: wiremock/wiremock:latest
    ports:
      - "8383:8080"
    volumes:
      - ./mappings:/home/wiremock/mappings
    environment:
      WILMOCK_PORT: 8080
      WILMOCK_ROOT_PORT: 8383
      WILMOCK_FILE_ENABLED: "true"
    command: --port 8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8383/__wiremock__/healthcheck"]
      interval: 5s
      timeout: 5s
      retries: 3

